### ISSUE TITLE
Compatibility with transient-mark-mode (highlighting the selection)

### ISSUE THREAD

**Issue by fice-t** [joddie/macrostep#14]
Would it be possible for the region to be highlighted like normal when in macrostepped code?

**Comment by fice-t** [comment]
@joddie I made a fix for this in #16, and it seems to work. Was the `priority` overlay property used for anything else besides checking if it was equal to 1?

**Comment by joddie** [comment]
Yes, the `priority` overlay property has a special meaning to Emacs: when there are several overlays at a point, all with different values for `SOME-PROPERTY`, `priority` determines which of them overrides the other.  See the Elisp manual node "Overlay Properties".

I think your PR is probably good but I have a couple of questions which I will ask over there.

**Comment by joddie** [comment]
Forgot to add: `macrostep` needs to be able to determine the innermost overlay when there are multiple levels of expansion.  This is done by setting `priority` to higher values for each successive level of expansion, which explains why the `expand-and-collapse` test would fail without ti.

**Comment by fice-t** [comment]
Right, I was searching around in `macrostep.el` for explicit uses of `priority` and somehow thought that since it seemed to work in trivial cases that it wasn't actually being used as normal. My bad.
