### ISSUE TITLE
Buffer is modified after a macroexpansion

### ISSUE THREAD

**Issue by georgek** [joddie/macrostep#2]
If one simply expands then collapses a macro the buffer is marked as modified but it should not be.

**Comment by npostavs** [comment]
This messes up code which relies on jit-lock, like `nlinum-mode` for instance: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27281#14

If you want to reset the buffer modified status, why not just use `set-buffer-modified-p`?
