### ISSUE TITLE
Expand macro in another buffer

### ISSUE THREAD

**Issue by joca-bt** [joddie/macrostep#8]
Is there a way to expand the macro in another buffer, like ```slime``` or ```imacroexpand``` do, and continue the expansions there?

Two motivations:
- Not messing with the original buffer,
- Being able to see the original code being macrostepped.

**Comment by joddie** [comment]
No, this isn't currently possible, but I agree it would be a good feature.  In principle, it should be quite simple to implement: before expanding a macro, the source text would be copied into a new buffer, and then everything can proceed as normal within the new buffer.  We would probably set some kind of buffer-local flag in the temporary buffer to indicate that it should be deleted when dismissed.  There might also be a need to save the outermost macro-expansion environment, in the case of expanding something within a macrolet form.

The new expand-in-separate-buffer behaviour should be enabled or disabled by a defcustom.

I don't have much time to work on this right now, but I will do my best to look at it when I have time.

**Comment by joddie** [comment]
I think this is now possible if you set or customize `macrostep-expand-in-separate-buffer` to `t`.

**Comment by bbatsov** [comment]
Btw, seems to me it'd be best to have separate commands for the 2 types of macroexpansion, as sometimes you might want to do it inline and sometimes not.

**Comment by joddie** [comment]
How about a prefix arg? Then you can save one key-binding. Added to `master`.
